/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pkkbjmwayttftsneeuia"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBra2JqbXdheXR0ZnRzbmVldWlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNzg1NzEsImV4cCI6MjA3MTg1NDU3MX0.u6FhTFXD5-HH12Nxl_3s7aEyhRfIx_IWwT-q6Vz-4Fk"